# W1D1: Python for ML — NumPy Fundamentals

## Objective

Learn NumPy arrays, broadcasting, vectorised operations,
matrix multiplication, and basic statistics.

In [1]:
import numpy as np

In [2]:
array_1d = np.array([1, 2, 3, 4, 5])

array_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

array_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)

print("\n2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)

print("\n3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [3]:
numbers = np.array([10, 20, 30, 40])

result = numbers + 5

print("Original:", numbers)
print("After adding 5:", result)

Original: [10 20 30 40]
After adding 5: [15 25 35 45]


In [4]:
numbers = np.array([1, 2, 3, 4, 5])

squared = numbers ** 2
doubled = numbers * 2

print("Original:", numbers)
print("Squared:", squared)
print("Doubled:", doubled)

Original: [1 2 3 4 5]
Squared: [ 1  4  9 16 25]
Doubled: [ 2  4  6  8 10]


In [5]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

result = A @ B

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nA @ B:")
print(result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

A @ B:
[[19 22]
 [43 50]]


In [6]:
df = pd.read_csv("student_scores.csv")

print(df)

NameError: name 'pd' is not defined

In [7]:
import pandas as pd


In [8]:
df = pd.read_csv("student_scores.csv")

print(df)

   Hours_Studied  Exam_Score
0              1          45
1              2          50
2              3          55
3              4          60
4              5          65
5              6          70
6              7          75
7              8          80
8              9          85
9             10          90


In [9]:
scores = df["Exam_Score"].to_numpy()

mean_score = np.mean(scores)
std_score = np.std(scores)

print("Mean:", mean_score)
print("Standard deviation:", std_score)

Mean: 67.5
Standard deviation: 14.361406616345072


In [10]:
hours = df["Hours_Studied"].to_numpy()
scores = df["Exam_Score"].to_numpy()

correlation = np.corrcoef(hours, scores)[0, 1]

print("Correlation:", correlation)

Correlation: 1.0


In [11]:
test1 = np.array([1, 2, 3])
test2 = np.array([10, 20, 30])
test3 = np.array([5, 10, 15, 20])

print("Test 1:", test1 * 2)
print("Test 2:", test2 * 2)
print("Test 3:", test3 * 2)

Test 1: [2 4 6]
Test 2: [20 40 60]
Test 3: [10 20 30 40]


## Key Learnings

- NumPy arrays are useful for efficient numerical operations.
- 1D, 2D, and 3D arrays have different shapes and dimensions.
- Broadcasting allows operations between compatible arrays and scalars.
- Vectorised operations perform calculations without explicit Python loops.
- The @ operator performs matrix multiplication.
- NumPy can calculate mean, standard deviation, and correlation.

In [1]:
# W1D2: Pandas for Data Manipulation
# Cynaris AIML Internship

import pandas as pd

print("Pandas version:", pd.__version__)


Pandas version: 3.0.5
